# Generated by Django 4.1.5 on 2023-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('p', 'Human'), ('n', 'Nature'), ('l', 'life'), ('h', 'Health'), ('t', 'Technology')], max_length=20),
        ),
    ]
